### ISSUE TITLE
Setting up Visual Studios Project

### ISSUE THREAD

**Issue by repritchett92** [BrianGladman/gsl#4]
Hello Brian,

Thank you for your work in creating this very helpful software package. I am having trouble following the instructions in your gsl.readme file, and I think it is because I am still new to Visual Studio (I am using VS 2017). I have downloaded and unzipped all of the files in your git repository and have located the gsl.lib.sln and gsl.dll.sln files, however I am having trouble with the next steps. My understanding is that I need to open one of these solution files in Visual Studio and then build either the gsldefs or gslhdrs projects first before moving onto step 2 and building the static or dynamic library. However I am having trouble with this first step because I can't seem to setup the project correctly in Visual Studio. When I try to build gslhdrs none of the standary library headers can be found (for example: stdio.h). Would you be able to include a few steps prior to Step 1 in your readme that explain how to go from downloading the repository to setting up the appropriate solution in Visual Studio?

Thanks in advance for your help!
Robert

**Comment by BrianGladman** [comment]
Hi Robert,

From what you say, it seems that something is wrong with the way your Visual Studio setup is being configured for building GSL.   It will be easier to find a solution if we can use an email exchange to investigate what is wrong - could you let me have an email address so that we can do this?

**Comment by repritchett92** [comment]
Hello Brian,

Thank you for your quick reply! The best email to reach me at is pritcher@purdue.edu.

To clarify, when I create other projects in VS 2017 I am able to create source files and headers that compile and use libraries from the standard library such as #include<iostream> and #include<string>. However when I open the gsl.lib.sln file in VS and then try to build gslhdrs I get errors about not seeing the standard library headers. I have a feeling this is because I am not setting up the project for gsl.lib.sln in the right way or not locating it in the right place on my computer. The gsl-master file was not located in my VS Projects folder when I first tried this compilation. However, I then also tried the compilation after copy pasting gsl-master into my Projects folder.

Thanks for your help! Again I am relatively new to VS and C++ so this issue could be a misunderstanding on my part. I will look for your reply in my email.

**Comment by BrianGladman** [comment]
After further investigation it was found that the build failed because the Windows SDK version 8.1 originally identified in this build was not installed on Robert's PC.  The build has now been updated to use Windows SDK version 10.0.15063.0.  The gsl.readme file will be updated to indicate the need to set the SDK that will be used with the build.
